[tool.pyright]
exclude = ["**/node_modules", "**/__pycache__"]
include = ["./scripty"]
pythonVersion = "3.10"
typeCheckingMode = "strict"
useLibraryCodeForTypes = true

reportImportCycles = "warning"
reportIncompatibleMethodOverride = "none"
reportIncompatibleVariableOverride = "none"
reportMissingTypeStubs = "none"
reportOptionalMemberAccess = "warning"
reportOverlappingOverload = "none"
reportUnknownMemberType = "warning"
reportUnnecessaryTypeIgnoreComment = "error"
reportUntypedFunctionDecorator = "warning"

[tool.isort]
profile = "black"
